#!/usr/bin/env bash
# Bake the AUC table from shapedSmoother.dsp into auc_waveform.lib (same dir).
# Reads aucTblContent (the formula — your source of truth) from the .dsp,
# evaluates it in -double via faust2plot, writes `aucTbl = waveform{...}`.
#
#   ./auc.sh                            # uses ./shapedSmoother.dsp
#   ./auc.sh path/to/shapedSmoother.dsp
set -euo pipefail

src="${1:-shapedSmoother.dsp}"
[ -f "$src" ] || {
    echo "not found: $src" >&2
    exit 1
}
src="$(realpath "$src")"
dir="$(dirname "$src")"
out="$dir/auc_waveform.lib"
n=257

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat >"$work/gen.dsp" <<EOF
process = library("$src").aucTblContent;
EOF

# -I "$dir" lets an import("auc_waveform.lib") inside your .dsp resolve from its
# own directory (faust runs from the temp dir, so its cwd isn't yours).
(cd "$work" && faust2plot -double -I "$dir" gen.dsp >/dev/null)

tmp="$work/auc_waveform.lib"
{
    echo "// AUTO-GENERATED by auc.sh from $(basename "$src") — do not edit by hand."
    echo "// ${n}-point AUC level-compensation table, evaluated in double precision."
    "$work/gen" -n "$n" | awk -v n="$n" '
        { s=$0; sub(/;.*/,"",s); gsub(/^[ \t]+|[ \t]+$/,"",s)
          if (s ~ /^[+-]?[0-9]*\.?[0-9]+([eE][+-]?[0-9]+)?$/) v[m++]=s }
        END {
            if (m != n) { print "ERROR: got " m " values, expected " n > "/dev/stderr"; exit 1 }
            print "aucTbl = waveform{"
            line="    "
            for (i=0;i<m;i++) {
                line = line v[i] (i<m-1 ? "," : "")
                if ((i+1)%8==0 || i==m-1) { print line; line="    " } else line = line " "
            }
            print "};"
        }'
} >"$tmp"
mv "$tmp" "$out"

echo "wrote $out ($n points)"
